=== PackyNZ/B5WarsPublic/B5Wars/src/net/b5gamer/b5wars/io/unit/unit.dtd
<!ELEMENT unit-definition (unit)>

<!-- common unit elements -->
<!ELEMENT unit (specs,maneuvering?,combat-stats,service-history,traits?,adaptive-armor?,(ship-definition|fighter-definition))>
<!ATTLIST unit name CDATA #REQUIRED> <!-- unit name e.g. EA Hyperion Heavy Cruiser -->
<!ATTLIST unit model CDATA #IMPLIED> <!-- unit model e.g. Theta Model -->
<!ATTLIST unit hull CDATA #REQUIRED> <!-- base hull the unit is built on e.g. Hyperion -->
<!ATTLIST unit version CDATA #REQUIRED> <!-- version number e.g. 3 -->
<!ATTLIST unit author CDATA #IMPLIED> <!-- author of the unit e.g. AOG -->
<!ATTLIST unit source CDATA #IMPLIED> <!-- source of the unit e.g. SF -->

<!ELEMENT specs EMPTY>
<!ATTLIST specs type CDATA #REQUIRED> <!-- unit type e.g. Capital Ship -->
<!ATTLIST specs pointValue CDATA #REQUIRED> <!-- combat point cost of the unit e.g. 705 -->
<!ATTLIST specs rammingFactor CDATA #REQUIRED>	<!-- factor for ramming other units e.g. 290 -->

<!ELEMENT maneuvering EMPTY>
<!ATTLIST maneuvering turnCost CDATA #REQUIRED> <!-- speed based thrust cost to make a turn e.g. 2/3 or 1 -->
<!ATTLIST maneuvering turnDelay CDATA #REQUIRED> <!-- speed based mandatory movement delay between making turns e.g. 1/3 or 1 -->
<!ATTLIST maneuvering accelDecelCost CDATA #REQUIRED> <!-- thrust required to alter speed e.g. 3 -->
<!ATTLIST maneuvering pivotCost CDATA #IMPLIED> <!-- thrust required to perform a pivot e.g. 3+3 or 1 -->
<!ATTLIST maneuvering rollCost CDATA #IMPLIED> <!-- thrust required to perform a roll e.g. 2+2 or 1 -->

<!ELEMENT combat-stats EMPTY>
<!ATTLIST combat-stats fwdAftDefense CDATA #REQUIRED> <!-- defense when attacked from fore or aft e.g. 14 -->
<!ATTLIST combat-stats stbPortDefense CDATA #REQUIRED> <!-- defense when attacked from starboard or port e.g. 16 -->
<!ATTLIST combat-stats initiativeModifier CDATA #REQUIRED> <!-- modifier to initiative e.g. 0 -->

<!ELEMENT service-history (period-of-service+)>
<!ELEMENT period-of-service (#PCDATA)> <!-- may contain text relating to any special notes for this period -->
<!ATTLIST period-of-service faction CDATA #REQUIRED> <!-- name of the faction employing the unit e.g. EA -->
<!ATTLIST period-of-service inService CDATA #IMPLIED> <!-- start date for this period of service e.g. 2246 -->
<!ATTLIST period-of-service endedService CDATA #IMPLIED> <!-- end date for this period of service e.g. 2265 -->
<!ATTLIST period-of-service datePrefix CDATA #IMPLIED> <!-- prefix for service dates e.g. Y -->
<!ATTLIST period-of-service dateSuffix CDATA #IMPLIED> <!-- suffix for service dates e.g. ANH -->
<!ATTLIST period-of-service availability (Base|Common|Uncommon|Rare|Specialty|Unique) #REQUIRED> <!-- availability of the base hull or variant during this period -->
<!ATTLIST period-of-service maxAvailable CDATA #IMPLIED> <!-- maximum number of this unit that were available during this period e.g. 2 -->
<!ATTLIST period-of-service deployment (Unlimited|Limited|Restricted|Special) #IMPLIED> <!-- deployment limitation during this period -->
<!ATTLIST period-of-service deploymentPercentage CDATA #IMPLIED> <!-- only use for non-standard deployment percentages (e.g. not 10% or 33%), maximum percentage of combat points that can be spent on this unit e.g. 50% -->
<!ATTLIST period-of-service onlyOnePer CDATA #IMPLIED> <!-- limitation of only one unit per the specified amount of combat points available e.g. 5000 -->
<!ATTLIST period-of-service economicCost CDATA #IMPLIED> <!-- modifier to units economic cost during this period e.g. 4 or 25% -->

<!ELEMENT traits (trait*)>
<!ELEMENT trait EMPTY>
<!ATTLIST trait name CDATA #REQUIRED> <!-- name of the trait e.g. Command Bonus -->
<!ATTLIST trait value CDATA #IMPLIED> <!-- value of the trait (if any) e.g. 2 -->

<!ELEMENT adaptive-armor EMPTY>
<!ATTLIST adaptive-armor adaptiveArmor CDATA #REQUIRED> <!-- amount of adaptive armor points available e.g. 6 -->
<!ATTLIST adaptive-armor maxPerWeaponType CDATA #IMPLIED> <!-- maximum points that can be allocated per weapon type e.g. 3 -->
<!ATTLIST adaptive-armor pointsPreAssigned CDATA #IMPLIED> <!-- number of points that can be pre-assigned e.g. 3 -->

<!ELEMENT property EMPTY>
<!ATTLIST property name CDATA #REQUIRED> <!-- name of the property e.g. systemType -->
<!ATTLIST property value CDATA #REQUIRED> <!-- value of the property e.g. Thruster -->

<!-- ship specific elements -->
<!ELEMENT ship-definition (hit-location-charts,sections)>

<!ELEMENT hit-location-charts (hit-location-chart+)>
<!ELEMENT hit-location-chart (hit-location+)>
<!ATTLIST hit-location-chart name CDATA #REQUIRED> <!-- name of the hit location chart e.g. FORWARD HITS -->
<!ELEMENT hit-location (property*,hit-location*)>
<!ATTLIST hit-location class CDATA #REQUIRED> <!-- name of the Java class to use for the hit location e.g SystemHitLocation (see HitLocation class in javadocs) -->
<!ATTLIST hit-location from (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20) #REQUIRED> <!-- from value for range e.g. 1 -->
<!ATTLIST hit-location to (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20) #REQUIRED> <!-- to value for range e.g. 4 -->

<!ELEMENT sections (section+)>
<!ATTLIST sections generalHitLocationChart CDATA #IMPLIED> <!-- name of the hit location chart to use for general hits e.g. GENERAL HITS (see Trait.SAUCER in javadocs) -->
<!ELEMENT section (property*,systems?,section*)>
<!ATTLIST section name CDATA #REQUIRED> <!-- name of the section e.g. PRIMARY -->
<!ATTLIST section class CDATA #REQUIRED> <!-- name of the Java class to use for the section e.g StructureSection (see Section class in javadocs) -->
<!ATTLIST section arc CDATA #IMPLIED> <!-- arc this section covers for incoming fire purposes e.g. F60 or Arc(330, 60) -->
<!ATTLIST section hitLocationChart CDATA #IMPLIED> <!-- name of the hit location chart to use for the section e.g. PRIMARY HITS -->

<!ELEMENT systems (system*,weapon*)>
<!ELEMENT system (property*,system-icons?)>
<!ATTLIST system class CDATA #REQUIRED> <!-- name of the Java class to use for the system e.g Structure (see System class in javadocs) -->
<!ATTLIST system damageBoxes CDATA #IMPLIED> <!-- amount of damage the system can sustain before being destroyed e.g. 54 -->
<!ATTLIST system armor CDATA #IMPLIED> <!-- amount of armor protecting the system e.g. 5 -->
<!ATTLIST system arc CDATA #IMPLIED> <!-- arc for incoming fire and/or outgoing effects e.g. F60 or Arc(330, 60) -->
<!ATTLIST system name CDATA #IMPLIED> <!-- optional name of the system e.g. A -->
<!ATTLIST system power CDATA #IMPLIED> <!-- amount of power required for the system to function e.g. 3 -->
<!ELEMENT weapon (property*,weapon-icons?)>
<!ATTLIST weapon type CDATA #REQUIRED> <!-- the weapon type e.g Heavy Laser Cannon -->
<!ATTLIST weapon damageBoxes CDATA #IMPLIED> <!-- amount of damage the weapon can sustain before being destroyed e.g. 54 -->
<!ATTLIST weapon armor CDATA #REQUIRED> <!-- amount of armor protecting the weapon e.g. 4 -->
<!ATTLIST weapon arc CDATA #REQUIRED> <!-- arc for incoming fire and field of fire for the weapon e.g. FP60 or Arc(300, 60) -->
<!ATTLIST weapon number CDATA #IMPLIED> <!-- the weapon number e.g. 1 -->

<!ELEMENT system-icons ((system-icon|structure-icon)?,armor-icon?,power-icon?,arc-icon?)>
<!ELEMENT system-icon EMPTY>
<!ATTLIST system-icon x CDATA #REQUIRED> <!-- x position e.g. 100 -->
<!ATTLIST system-icon y CDATA #REQUIRED> <!-- y position e.g. 100 -->
<!ATTLIST system-icon mirror (true|false) #IMPLIED> <!-- whether to mirror the icon -->
<!ATTLIST system-icon rotation CDATA #IMPLIED> <!-- number of degrees to rotate the icon e.g. 90 -->
<!ATTLIST system-icon index CDATA #IMPLIED> <!-- icon number e.g. 2 -->
<!ELEMENT structure-icon EMPTY>
<!ATTLIST structure-icon x CDATA #REQUIRED> <!-- x position e.g. 100 -->
<!ATTLIST structure-icon y CDATA #REQUIRED> <!-- y position e.g. 100 -->
<!ATTLIST structure-icon mirror (true|false) #IMPLIED> <!-- whether to mirror the icon -->
<!ATTLIST structure-icon rotation CDATA #IMPLIED> <!-- number of degrees to rotate the icon e.g. 90 -->
<!ATTLIST structure-icon definition CDATA #IMPLIED> <!-- custom icon definition for specific systems such as structure e.g -->
<!ELEMENT weapon-icons (weapon-icon?,armor-icon?,power-icon?,arc-icon?,number-icon?)>
<!ELEMENT weapon-icon EMPTY>
<!ATTLIST weapon-icon x CDATA #REQUIRED> <!-- x position e.g. 100 -->
<!ATTLIST weapon-icon y CDATA #REQUIRED> <!-- y position e.g. 100 -->
<!ATTLIST weapon-icon mirror (true|false) #IMPLIED> <!-- whether to mirror the icon -->
<!ATTLIST weapon-icon rotation CDATA #IMPLIED> <!-- number of degrees to rotate the icon e.g. 90 -->
<!ELEMENT armor-icon EMPTY>
<!ATTLIST armor-icon x CDATA #REQUIRED> <!-- x position e.g. 100 -->
<!ATTLIST armor-icon y CDATA #REQUIRED> <!-- y position e.g. 100 -->
<!ELEMENT power-icon EMPTY>
<!ATTLIST power-icon x CDATA #REQUIRED> <!-- x position e.g. 100 -->
<!ATTLIST power-icon y CDATA #REQUIRED> <!-- y position e.g. 100 -->
<!ELEMENT arc-icon EMPTY>
<!ATTLIST arc-icon x CDATA #REQUIRED> <!-- x position e.g. 100 -->
<!ATTLIST arc-icon y CDATA #REQUIRED> <!-- y position e.g. 100 -->
<!ELEMENT number-icon EMPTY>
<!ATTLIST number-icon x CDATA #REQUIRED> <!-- x position e.g. 100 -->
<!ATTLIST number-icon y CDATA #REQUIRED> <!-- y position e.g. 100 -->

<!-- fighter specific elements -->
<!ELEMENT fighter-definition (fighter-combat-stats)>

<!ELEMENT fighter-combat-stats EMPTY>
<!ATTLIST fighter-combat-stats freeThrust CDATA #REQUIRED> <!-- available thrust per turn e.g. 12 -->
<!ATTLIST fighter-combat-stats offensiveModifier CDATA #REQUIRED> <!-- attack modifier e.g. 5 -->
<!ATTLIST fighter-combat-stats dropoutModifier CDATA #IMPLIED> <!-- modifier to dropout rolls e.g. 0 -->

=== PackyNZ/B5WarsPublic/B5Wars/src/net/b5gamer/b5wars/io/unit/Dilgar Mishakur Dreadnought.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE unit-definition SYSTEM "unit.dtd">

<unit-definition>
	<unit name="Dilgar Mishakur Dreadnought" hull="Mishakur" version="1" author="AOG" source="DW">			
		<specs type="Capital Ship" pointValue="975" rammingFactor="310" />
		<maneuvering turnCost="1" turnDelay="1" accelDecelCost="4" pivotCost="4+4" rollCost="2+2" /> 		
		<combat-stats fwdAftDefense="16" stbPortDefense="17" initiativeModifier="0" />
		<service-history>
			<period-of-service faction="Dilgar" inService="2227" endedService="2232" availability="Base" deployment="Restricted" />
		</service-history>
		<!-- <influence modifies="Initiative" modifier="2" appliesTo="Command" /> -->
		<traits>
			<trait name="Command Bonus" value="2" />
		</traits>						
								
		<ship-definition>	
			<hit-location-charts>		
				<hit-location-chart name="FORWARD HITS">	 	
					<hit-location class="SystemHitLocation" from="1" to="4">
						<property name="systemType" value="Thruster" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="5" to="6">
						<property name="systemType" value="Heavy Bolter" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="7" to="8">
						<property name="systemType" value="Scatter-Pulsar" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="9" to="10">
						<property name="systemType" value="Medium Laser Cannon" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="11" to="18">
						<property name="systemType" value="Structure" />
					</hit-location>
					<hit-location class="SectionHitLocation" from="19" to="20">
						<property name="sectionName" value="PRIMARY" />
					</hit-location>
				</hit-location-chart>
				
				<hit-location-chart name="SIDE HITS">	 	
					<hit-location class="SystemHitLocation" from="1" to="4">
						<property name="systemType" value="Thruster" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="5" to="6">
						<property name="systemType" value="Heavy Bolter" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="7" to="8">
						<property name="systemType" value="Quad Pulsar" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="9" to="9">
						<property name="systemType" value="Plasma Torch" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="10" to="10">
						<property name="systemType" value="Class-S Missile Rack" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="11" to="11">
						<property name="systemType" value="Scatter-Pulsar" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="12" to="18">
						<property name="systemType" value="Structure" />
					</hit-location>
					<hit-location class="SectionHitLocation" from="19" to="20">
						<property name="sectionName" value="PRIMARY" />
					</hit-location>
				</hit-location-chart>
		
				<hit-location-chart name="AFT HITS">	 	
					<hit-location class="SystemHitLocation" from="1" to="6">
						<property name="systemType" value="Thruster" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="7" to="8">
						<property name="systemType" value="Heavy Bolter" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="9" to="10">
						<property name="systemType" value="Scatter-Pulsar" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="11" to="11">
						<property name="systemType" value="Engine" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="12" to="18">
						<property name="systemType" value="Structure" />
					</hit-location>
					<hit-location class="SectionHitLocation" from="19" to="20">
						<property name="sectionName" value="PRIMARY" />
					</hit-location>
				</hit-location-chart>
		
				<hit-location-chart name="PRIMARY HITS">			
					<hit-location class="SystemHitLocation" from="1" to="10">
						<property name="systemType" value="Structure" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="11" to="12">
						<property name="systemType" value="Jump Engine" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="13" to="14">
						<property name="systemType" value="Sensors" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="15" to="16">
						<property name="systemType" value="Engine" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="17" to="17">
						<property name="systemType" value="Hangar" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="18" to="19">
						<property name="systemType" value="Reactor" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="20" to="20">
						<property name="systemType" value="C &amp; C" />
					</hit-location>
				</hit-location-chart>
			</hit-location-charts>
			
			<sections>
				<section name="FORWARD" class="StructureSection" arc="F60" hitLocationChart="FORWARD HITS">
					<systems>
						<system class="Structure" damageBoxes="54" armor="5" />
						<system class="Thruster" damageBoxes="10" armor="3" arc="F120">
							<property name="thrustRating" value="3" />
						</system>					
						<system class="Thruster" damageBoxes="10" armor="3" arc="F120">
							<property name="thrustRating" value="3" />
						</system>					
						<weapon type="Heavy Bolter" armor="3" arc="FP60" number="2" />					
						<weapon type="Heavy Bolter" armor="3" arc="FS60" number="3" />					
						<weapon type="Medium Laser Cannon" armor="2" arc="F120" number="9" />					
						<weapon type="Medium Laser Cannon" armor="2" arc="F120" number="10" />					
						<weapon type="Scatter-Pulsar" armor="1" arc="F240" number="13" />						
						<weapon type="Scatter-Pulsar" armor="1" arc="F240" number="14" />
					</systems>
				</section>
			
				<section name="PORT" class="StructureSection" arc="P120" hitLocationChart="SIDE HITS">
					<systems>
						<system class="Structure" damageBoxes="60" armor="5" />
						<system class="Thruster" damageBoxes="15" armor="3" arc="P120">
							<property name="thrustRating" value="5" />
						</system>					
						<weapon type="Heavy Bolter" armor="3" arc="FP60" number="1" />					
						<weapon type="Quad Pulsar" armor="3" arc="FP60" number="7" />					
						<weapon type="Class-S Missile Rack" armor="2" arc="F240" number="11" />					
						<weapon type="Plasma Torch" armor="1" arc="FP120" number="13" />
						<weapon type="Scatter-Pulsar" armor="1" arc="FP240" number="15" />
					</systems>
				</section>
		
				<section name="PRIMARY" class="StructureSection" hitLocationChart="PRIMARY HITS">
					<systems>
						<system class="Structure" damageBoxes="64" armor="6" />
						<system class="CommandAndControl" damageBoxes="25" armor="6" />
						<system class="Sensors" damageBoxes="16" armor="5" power="3">
							<property name="sensorRating" value="9" />
						</system>					
						<system class="Engine" damageBoxes="13" armor="5">
							<property name="freeThrust" value="7" />
							<property name="efficiency" value="3/1" />
						</system>					
						<system class="JumpEngine" damageBoxes="16" armor="4" power="4">
							<property name="jumpDelay" value="36" />
						</system>					
						<system class="Reactor" damageBoxes="25" armor="5">
							<property name="availablePower" value="77" />
						</system>					
						<system class="Hangar" damageBoxes="14" armor="4">
							<property name="launchRate" value="6" />
						</system>					
					</systems>
				</section>
		
				<section name="STARBOARD" class="StructureSection" arc="S120" hitLocationChart="SIDE HITS">
					<systems>
						<system class="Structure" damageBoxes="60" armor="5" />
						<system class="Thruster" damageBoxes="15" armor="3" arc="S120">
							<property name="thrustRating" value="5" />
						</system>					
						<weapon type="Heavy Bolter" armor="3" arc="FS60" number="4" />					
						<weapon type="Quad Pulsar" armor="3" arc="FS60" number="8" />					
						<weapon type="Class-S Missile Rack" armor="2" arc="F240" number="12" />					
						<weapon type="Plasma Torch" armor="1" arc="FS120" number="14" />
						<weapon type="Scatter-Pulsar" armor="1" arc="FS240" number="16" />
					</systems>
				</section>
			
				<section name="AFT" class="StructureSection" arc="A60" hitLocationChart="AFT HITS">
					<systems>
						<system class="Structure" damageBoxes="54" armor="5" />
						<system class="Thruster" damageBoxes="6" armor="2" arc="A120">
							<property name="thrustRating" value="2" />
						</system>					
						<system class="Thruster" damageBoxes="10" armor="3" arc="A120">
							<property name="thrustRating" value="4" />
						</system>					
						<system class="Thruster" damageBoxes="10" armor="3" arc="A120">
							<property name="thrustRating" value="4" />
						</system>					
						<system class="Thruster" damageBoxes="6" armor="2" arc="A120">
							<property name="thrustRating" value="2" />
						</system>
						<system class="Engine" damageBoxes="11" armor="3">
							<property name="freeThrust" value="5" />
							<property name="efficiency" value="3/1" />
						</system>					
						<weapon type="Heavy Bolter" armor="3" arc="AP60" number="5" />					
						<weapon type="Heavy Bolter" armor="3" arc="AS60" number="6" />					
						<weapon type="Scatter-Pulsar" armor="1" arc="AP240" number="17" />
						<weapon type="Scatter-Pulsar" armor="1" arc="AS240" number="18" />
					</systems>
				</section>
			</sections>
		</ship-definition>						
	</unit>				
</unit-definition>

=== PackyNZ/B5WarsPublic/B5Wars/src/net/b5gamer/b5wars/io/unit/EA Epimetheus Jump Cruiser (Epsilon Model).xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE unit-definition SYSTEM "unit.dtd">

<unit-definition>
	<unit name="EA Epimetheus Jump Cruiser" model="Epsilon Model" hull="Epimetheus" version="2" author="RLB" source="EW">			
		<specs type="Capital Ship" pointValue="560" rammingFactor="220" />
		<maneuvering turnCost="1" turnDelay="1" accelDecelCost="2" pivotCost="2+2" rollCost="2+2" /> 		
		<combat-stats fwdAftDefense="14" stbPortDefense="15" initiativeModifier="0" />
		<service-history>
			<period-of-service faction="EA" inService="2193" availability="Base" deployment="Unlimited" />
		</service-history>
		<!-- <unreliabilities>
			<unreliability name="Power Fluctuations" />
		</unreliabilities> -->
		<traits>
			<trait name="Unreliable Ship" value="Power Fluctuations" />
		</traits>	
		
		<ship-definition>	
			<hit-location-charts>		
				<hit-location-chart name="FORWARD HITS">	 	
					<hit-location class="SystemHitLocation" from="1" to="5">
						<property name="systemType" value="Thruster" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="6" to="7">
						<property name="systemType" value="Particle Cannon" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="8" to="10">
						<property name="systemType" value="Interceptor Mk-I" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="11" to="18">
						<property name="systemType" value="Structure" />
					</hit-location>
					<hit-location class="SectionHitLocation" from="19" to="20">
						<property name="sectionName" value="PRIMARY" />
					</hit-location>
				</hit-location-chart>
				
				<hit-location-chart name="SIDE HITS">	 	
					<hit-location class="SystemHitLocation" from="1" to="4">
						<property name="systemType" value="Thruster" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="5" to="6">
						<property name="systemType" value="Medium Plasma Cannon" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="7" to="10">
						<property name="systemType" value="Railgun" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="11" to="18">
						<property name="systemType" value="Structure" />
					</hit-location>
					<hit-location class="SectionHitLocation" from="19" to="20">
						<property name="sectionName" value="PRIMARY" />
					</hit-location>
				</hit-location-chart>
		
				<hit-location-chart name="AFT HITS">	 	
					<hit-location class="SystemHitLocation" from="1" to="6">
						<property name="systemType" value="Thruster" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="7" to="8">
						<property name="systemType" value="Medium Plasma Cannon" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="9" to="9">
						<property name="systemType" value="Interceptor Mk-I" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="10" to="12">
						<property name="systemType" value="Jump Engine" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="13" to="18">
						<property name="systemType" value="Structure" />
					</hit-location>
					<hit-location class="SectionHitLocation" from="19" to="20">
						<property name="sectionName" value="PRIMARY" />
					</hit-location>
				</hit-location-chart>
		
				<hit-location-chart name="PRIMARY HITS">			
					<hit-location class="SystemHitLocation" from="1" to="10">
						<property name="systemType" value="Structure" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="11" to="12">
						<property name="systemType" value="Standard Particle Beam" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="13" to="14">
						<property name="systemType" value="Sensors" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="15" to="16">
						<property name="systemType" value="Engine" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="17" to="18">
						<property name="systemType" value="Hangar" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="19" to="19">
						<property name="systemType" value="Reactor" />
					</hit-location>
					<hit-location class="SystemHitLocation" from="20" to="20">
						<property name="systemType" value="C &amp; C" />
					</hit-location>
				</hit-location-chart>
			</hit-location-charts>
			
			<sections>
				<section name="FORWARD" class="StructureSection" arc="F60" hitLocationChart="FORWARD HITS">
					<systems>
						<system class="Structure" damageBoxes="50" armor="4" />
						<system class="Thruster" damageBoxes="8" armor="3" arc="F120">
							<property name="thrustRating" value="3" />
						</system>					
						<system class="Thruster" damageBoxes="8" armor="3" arc="F120">
							<property name="thrustRating" value="3" />
						</system>					
						<weapon type="Particle Cannon" armor="3" arc="F120" number="3" />					
						<weapon type="Interceptor Mk-I" armor="2" arc="FP120" number="9" />						
						<weapon type="Interceptor Mk-I" armor="2" arc="FS120" number="10" />
					</systems>
				</section>
			
				<section name="PORT" class="StructureSection" arc="P120" hitLocationChart="SIDE HITS">
					<systems>
						<system class="Structure" damageBoxes="48" armor="4" />
						<system class="Thruster" damageBoxes="13" armor="3" arc="P120">
							<property name="thrustRating" value="4" />
						</system>					
						<weapon type="Railgun" armor="4" arc="FP60" number="1" />
						<weapon type="Medium Plasma Cannon" armor="3" arc="P180" number="4" />					
					</systems>
				</section>
		
				<section name="PRIMARY" class="StructureSection" hitLocationChart="PRIMARY HITS">
					<systems>
						<system class="Structure" damageBoxes="40" armor="4" />
						<system class="CommandAndControl" damageBoxes="16" armor="4" />
						<system class="Sensors" damageBoxes="14" armor="4" power="4">
							<property name="sensorRating" value="6" />
						</system>					
						<system class="Engine" damageBoxes="11" armor="4">
							<property name="freeThrust" value="6" />
							<property name="efficiency" value="4/1" />
						</system>					
						<system class="Reactor" damageBoxes="23" armor="4">
							<property name="availablePower" value="40" />
						</system>					
						<system class="Hangar" damageBoxes="2" armor="4">
							<property name="launchRate" value="2" />
						</system>					
						<weapon type="Standard Particle Beam" armor="2" arc="360" number="7" />
						<weapon type="Standard Particle Beam" armor="2" arc="360" number="8" />
					</systems>
				</section>
		
				<section name="STARBOARD" class="StructureSection" arc="S120" hitLocationChart="SIDE HITS">
					<systems>
						<system class="Structure" damageBoxes="48" armor="4" />
						<system class="Thruster" damageBoxes="13" armor="3" arc="S120">
							<property name="thrustRating" value="4" />
						</system>					
						<weapon type="Railgun" armor="4" arc="FS60" number="2" />
						<weapon type="Medium Plasma Cannon" armor="3" arc="S180" number="5" />					
					</systems>
				</section>
			
				<section name="AFT" class="StructureSection" arc="A60" hitLocationChart="AFT HITS">
					<systems>
						<system class="Structure" damageBoxes="36" armor="3" />
						<system class="Thruster" damageBoxes="7" armor="3" arc="A120">
							<property name="thrustRating" value="2" />
						</system>					
						<system class="Thruster" damageBoxes="7" armor="3" arc="A120">
							<property name="thrustRating" value="2" />
						</system>					
						<system class="Thruster" damageBoxes="7" armor="3" arc="A120">
							<property name="thrustRating" value="2" />
						</system>
						<system class="JumpEngine" damageBoxes="20" armor="4" power="3">
							<property name="jumpDelay" value="30" />
						</system>					
						<weapon type="Medium Plasma Cannon" armor="3" arc="A120" number="6" />
						<weapon type="Interceptor Mk-I" armor="2" arc="A180" number="11" />
					</systems>
				</section>
			</sections>
		</ship-definition>						
	</unit>				
</unit-definition>
